#!/usr/bin/env python3
"""
SKILL-DOCUMENT-ONLY LLM BASELINE -- re-run with the PAPER'S OWN MODEL.

Closes the "you used a different model (gemini)" objection: the CTA paper's
traces were generated by Claude Sonnet 4.5, so the skill-only baseline is
re-run here with claude-sonnet-4.5 on the Anthropic-native /v1/messages API.

Two arms, both on all 49 tasks:
  --variant hard      : IDENTICAL system+user prompt to the gemini / opus-4.8
                        runs (imported verbatim from skill_only_baseline_run.py).
  --variant baserate  : same prompt + an explicit statement of the empirical
                        base rate (45/49 tasks have dP == 0). This is the
                        pre-registered answer to the reviewer objection that the
                        6.1%-vs-91.8% gap merely reflects base-rate ignorance
                        rather than non-recoverability.

Credentials come from <REPO_ROOT>/rebuttal/.sonnet_env and are NEVER
printed, logged, or written to any output file.

Usage:
  /usr/bin/python3.12 skill_only_baseline_sonnet_run.py \
      --model claude-sonnet-4.5 --variant hard \
      --out <REPO_ROOT>/rebuttal/results/skill_only_baseline_sonnet
"""
import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path("<REPO_ROOT>/rebuttal")
sys.path.insert(0, str(ROOT / "scripts"))

# Reuse the EXACT prompts + parser from the original run so the cross-model
# comparison is apples-to-apples. Do not restate them here.
from skill_only_baseline_run import (  # noqa: E402
    SYSTEM_PROMPT, USER_TMPL, parse_json, SKILLS, TASKS,
)

# ---------------------------------------------------------------------------
# BASE-RATE ARM. The ONLY delta vs SYSTEM_PROMPT is this paragraph, inserted
# immediately before the output-format instruction. No per-task information is
# revealed -- only the corpus-level marginal distribution of dP.
# ---------------------------------------------------------------------------
BASERATE_BLOCK = """EMPIRICAL BASE RATE FOR THIS CORPUS (important). These skills were evaluated
on a benchmark of 49 software-engineering tasks. Across that corpus, the large
majority of skills produced NO measurable change in the unit-test pass rate:
45 of the 49 tasks (91.8%) had a pass-rate delta of exactly zero. Only 4 tasks
moved at all, and those moved by small amounts in both directions. Baseline
(no-skill) pass rates are already high (mean 0.889), so there is very little
headroom for a skill to help and most behavioural differences wash out before
they reach the test suite.

Take this base rate seriously. Predict "raise" or "lower" ONLY when this
particular document gives you a specific, concrete reason to expect a
measurable change in the number of passing unit tests on this particular task.
Otherwise predict "no_change". You are not being rewarded for decisiveness.

"""

SYSTEM_PROMPT_BASERATE = SYSTEM_PROMPT.replace(
    "Answer with a single strict JSON object and nothing else.",
    BASERATE_BLOCK + "Answer with a single strict JSON object and nothing else.",
)
assert SYSTEM_PROMPT_BASERATE != SYSTEM_PROMPT, "base-rate insertion failed"


def load_env(path=ROOT / ".sonnet_env"):
    env = {}
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def call_anthropic(base, key, model, system, user, temperature=0.0,
                   max_tok=2000, retries=5):
    """POST {base}/v1/messages -- Anthropic-native, the paper model's own API."""
    url = base.rstrip("/") + "/v1/messages"
    body = {
        "model": model,
        "max_tokens": max_tok,
        "temperature": temperature,
        "system": system,
        "messages": [{"role": "user", "content": user}],
    }
    data = json.dumps(body).encode()
    last = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(
                url, data=data,
                headers={"x-api-key": key,
                         "anthropic-version": "2023-06-01",
                         "content-type": "application/json"},
            )
            with urllib.request.urlopen(req, timeout=300) as r:
                return json.loads(r.read().decode())
        except Exception as e:  # noqa: BLE001
            last = e
            detail = ""
            if isinstance(e, urllib.error.HTTPError):
                try:
                    detail = e.read().decode()[:300]
                except Exception:  # noqa: BLE001
                    pass
            sys.stderr.write(f"[retry {attempt+1}] {type(e).__name__} {detail}\n")
            time.sleep(5 * (attempt + 1))
    raise RuntimeError(f"all retries failed: {type(last).__name__}")


def text_of(resp):
    return "".join(b.get("text", "") for b in (resp.get("content") or [])
                   if b.get("type") == "text")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="claude-sonnet-4.5")
    ap.add_argument("--out", required=True)
    ap.add_argument("--tasks", default="")
    ap.add_argument("--temperature", type=float, default=0.0)
    ap.add_argument("--max-tok", type=int, default=2000)
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--variant", default="hard", choices=["hard", "baserate"])
    args = ap.parse_args()

    env = load_env()
    base = env["SONNET_ANTHROPIC_BASE"]
    key = env["SONNET_KEY"]

    SYS = SYSTEM_PROMPT if args.variant == "hard" else SYSTEM_PROMPT_BASERATE
    tag = args.model if args.variant == "hard" else f"{args.model}-baserate"
    outdir = Path(args.out)
    rawdir = outdir / "raw"
    rawdir.mkdir(parents=True, exist_ok=True)

    task_ids = sorted(p.name for p in SKILLS.iterdir() if (p / "SKILL.md").exists())
    if args.tasks:
        want = set(args.tasks.split(","))
        task_ids = [t for t in task_ids if t in want]
    print(f"[info] model={args.model} variant={args.variant} "
          f"tasks={len(task_ids)} temp={args.temperature}")

    (outdir / f"prompt_template_{tag}.txt").write_text(
        "=== SYSTEM ===\n" + SYS + "\n\n=== USER TEMPLATE ===\n" + USER_TMPL
    )

    def work(tid):
        skill_md = (SKILLS / tid / "SKILL.md").read_text()
        tmd_p = TASKS / f"{tid}.md"
        task_md = tmd_p.read_text() if tmd_p.exists() else "(no task description file)"
        user = USER_TMPL.format(task_id=tid, task_md=task_md, skill_md=skill_md)
        t0 = time.time()
        resp = call_anthropic(base, key, args.model, SYS, user,
                              args.temperature, args.max_tok)
        dt = time.time() - t0
        content = text_of(resp)
        u = resp.get("usage", {}) or {}
        usage = {  # normalise to the OpenAI-style keys the scorer/aggregator uses
            "prompt_tokens": u.get("input_tokens", 0),
            "completion_tokens": u.get("output_tokens", 0),
            "total_tokens": u.get("input_tokens", 0) + u.get("output_tokens", 0),
            "cache_creation_input_tokens": u.get("cache_creation_input_tokens", 0),
            "cache_read_input_tokens": u.get("cache_read_input_tokens", 0),
        }
        rec = {
            "task_id": tid, "model": tag, "api": "anthropic-messages",
            "model_id_requested": args.model,
            "temperature": args.temperature,
            "stop_reason": resp.get("stop_reason"),
            "latency_s": round(dt, 2),
            "usage": usage,
            "raw_content": content,
            "parsed": parse_json(content),
            "user_prompt_chars": len(user),
        }
        (rawdir / f"{tag}__{tid}.json").write_text(json.dumps(rec, indent=1))
        p = rec["parsed"] or {}
        print(f"  {tid:42s} {str(p.get('pass_rate_effect')):10s} "
              f"{str(p.get('dominant_sip')):24s} conf={p.get('confidence')} "
              f"[{usage['prompt_tokens']}+{usage['completion_tokens']}tok {dt:.0f}s]")
        return rec

    results = []
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futs = {ex.submit(work, t): t for t in task_ids}
        for f in as_completed(futs):
            try:
                results.append(f.result())
            except Exception as e:  # noqa: BLE001
                print(f"  [FAIL] {futs[f]}: {e}")
                results.append({"task_id": futs[f], "model": tag,
                                "error": str(e), "parsed": None, "usage": {}})

    results.sort(key=lambda r: r["task_id"])
    (outdir / f"predictions_{tag}.json").write_text(json.dumps(results, indent=1))

    pt = sum((r.get("usage") or {}).get("prompt_tokens", 0) for r in results)
    ct = sum((r.get("usage") or {}).get("completion_tokens", 0) for r in results)
    ok = sum(1 for r in results if r.get("parsed"))
    # Anthropic list price for the Sonnet 4.5 tier, USD per 1M tokens.
    usd = pt / 1e6 * 3.0 + ct / 1e6 * 15.0
    print(f"[done] parsed_ok={ok}/{len(results)} prompt_tokens={pt} "
          f"completion_tokens={ct} est_usd={usd:.4f}")
    (outdir / f"usage_{tag}.json").write_text(json.dumps(
        {"model": tag, "model_id_requested": args.model,
         "api": "anthropic-messages", "variant": args.variant,
         "n_calls": len(results), "parsed_ok": ok,
         "prompt_tokens": pt, "completion_tokens": ct, "total_tokens": pt + ct,
         "est_usd_at_list_3in_15out": round(usd, 4)}, indent=1))


if __name__ == "__main__":
    main()
