#!/usr/bin/env python3
"""
Score the SKILL-DOCUMENT-ONLY baseline for the PAPER'S OWN MODEL (Sonnet 4.5)
and compare it head-to-head with the earlier gemini / opus-4.8 runs.

Every statistic is computed by the IDENTICAL code used for the gemini run:
score_model, cohen_kappa, perm_p, wilson and mcnemar_exact are imported from
skill_only_baseline_score.py, not reimplemented.

Adds three things the original scorer did not report:
  (1) dP-sign Cohen's kappa + permutation p (the original only gave accuracy,
      Wilson CI and McNemar-vs-majority).
  (2) The BASE-RATE ARM: identical prompt plus an explicit statement that
      45/49 tasks have dP == 0. Tests whether the headline gap is base-rate
      ignorance rather than non-recoverability.
  (3) A full cross-model agreement matrix (LLM-vs-LLM against LLM-vs-CTA).
"""
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path("<REPO_ROOT>/rebuttal")
sys.path.insert(0, str(ROOT / "scripts"))

from skill_only_baseline_score import (  # noqa: E402
    load_truth, cohen_kappa, perm_p, wilson, mcnemar_exact,
    score_model, SIPS, EFFECTS, EFF2SIGN,
)

OLD = ROOT / "results" / "skill_only_baseline"
NEW = ROOT / "results" / "skill_only_baseline_sonnet"
NEW.mkdir(parents=True, exist_ok=True)

ARMS = [
    ("claude-sonnet-4.5", NEW, "paper's own model, IDENTICAL prompt to gemini run"),
    ("claude-sonnet-4.5-baserate", NEW, "same + explicit 45/49 base rate stated"),
    ("gemini", OLD, "prior run, all 49"),
    ("claude-opus-4.8", OLD, "prior run, 15-task subset"),
]


def dp_supplement(model, outdir, truth, lines):
    """dP-sign stats the original scorer did not print: kappa, perm p,
    no_change count, and discrimination on the 4 tasks that actually moved."""
    preds = {r["task_id"]: (r.get("parsed") or {})
             for r in json.load(open(outdir / f"predictions_{model}.json"))}
    tasks = sorted(preds)
    pairs = [(truth[t]["dp_sign"], EFF2SIGN.get(preds[t].get("pass_rate_effect")))
             for t in tasks]
    n = len(pairs)
    acc = sum(1 for a, b in pairs if a == b)
    gt = Counter(a for a, _ in pairs)
    maj_n = gt.most_common(1)[0][1]
    nc = sum(1 for t in tasks if preds[t].get("pass_rate_effect") == "no_change")
    movers = [t for t in tasks if truth[t]["dp_sign"] != 0]
    mov_hit = sum(1 for t in movers
                  if EFF2SIGN.get(preds[t].get("pass_rate_effect")) == truth[t]["dp_sign"])
    lo, hi = wilson(acc, n)
    mlo, mhi = wilson(maj_n, n)
    k = cohen_kappa(pairs, [-1, 0, 1])
    p = perm_p(pairs, [-1, 0, 1])
    lines.append(f"\n  [A-suppl] dP-sign extras for {model} (n={n})")
    lines.append(f"    accuracy                 {acc}/{n} = {acc/n:.1%}  "
                 f"Wilson95 [{lo:.1%}, {hi:.1%}]")
    lines.append(f"    majority-class baseline  {maj_n}/{n} = {maj_n/n:.1%}  "
                 f"Wilson95 [{mlo:.1%}, {mhi:.1%}]")
    lines.append(f"    Cohen's kappa vs measured dP-sign : {k:+.3f}")
    lines.append(f"    permutation p (acc >= obs)        : {p:.4g}")
    lines.append(f"    n predicted 'no_change'           : {nc}/{n} "
                 f"({nc/n:.1%})")
    lines.append(f"    recall on the {len(movers)} tasks that ACTUALLY moved: "
                 f"{mov_hit}/{len(movers)}")
    return {"model": model, "n": n, "acc": acc, "maj": maj_n, "kappa": k,
            "perm_p": p, "n_no_change": nc, "movers": len(movers),
            "mover_hits": mov_hit, "preds": preds, "tasks": tasks,
            "wilson": (lo, hi)}


def main():
    truth = load_truth()
    lines = []
    lines.append("SKILL-DOCUMENT-ONLY LLM BASELINE -- PAPER'S OWN MODEL (Claude Sonnet 4.5)")
    lines.append("=" * 78)
    lines.append("The CTA paper's 49 traces were generated by Claude Sonnet 4.5. The earlier")
    lines.append("skill-only baseline used 'gemini', which invited the objection that a")
    lines.append("different model was being asked to reproduce Sonnet's behaviour. This run")
    lines.append("repeats the IDENTICAL protocol with claude-sonnet-4.5 itself.")
    lines.append("")
    lines.append("MODEL-ID CAVEAT: the pinned snapshot claude-sonnet-4-5-20250929 that the")
    lines.append("paper used is not reachable on this API key; only the moving alias")
    lines.append("'claude-sonnet-4.5' is served. The alias may resolve to a later 4.5")
    lines.append("point release than the one that produced the traces.")
    lines.append("")
    lines.append("The model sees ONLY <task>.md + <task>/SKILL.md. No execution trace, no")
    lines.append("CTA output. This is a LOWER BOUND on a trace-reading LLM baseline.")
    lines.append(f"\nGround truth over all 49 tasks: dP-sign distribution "
                 f"{dict(Counter(truth[t]['dp_sign'] for t in truth))}")

    out, sup = {}, {}
    for model, d, note in ARMS:
        if not (d / f"predictions_{model}.json").exists():
            lines.append(f"\n[skip] {model}: no predictions file")
            continue
        lines.append(f"\n\n### ARM: {model}  ({note})")
        out[model] = score_model(model, truth, lines, outdir=d)
        sup[model] = dp_supplement(model, d, truth, lines)

    # ------------------------------------------------------------------ #
    # BASE-RATE ARM verdict
    # ------------------------------------------------------------------ #
    lines.append(f"\n{'='*78}\nBASE-RATE ABLATION VERDICT (reviewer counterattack #1)\n{'='*78}")
    h, b = sup.get("claude-sonnet-4.5"), sup.get("claude-sonnet-4.5-baserate")
    if h and b:
        lines.append("Objection: 'the model was never told that 45/49 tasks have dP==0, so the")
        lines.append("6.1%-vs-91.8% gap is base-rate ignorance, not non-recoverability.'")
        lines.append("")
        lines.append(f"  arm             dP-sign acc   n_no_change   kappa    movers found")
        for tag, r in (("no base rate", h), ("base rate given", b)):
            lines.append(f"  {tag:15s} {r['acc']:2d}/{r['n']} = {r['acc']/r['n']:5.1%}   "
                         f"{r['n_no_change']:2d}/{r['n']}       {r['kappa']:+.3f}    "
                         f"{r['mover_hits']}/{r['movers']}")
        lines.append(f"  majority-class  {b['maj']:2d}/{b['n']} = {b['maj']/b['n']:5.1%}   "
                     f"{b['n']:2d}/{b['n']}       {0.0:+.3f}    0/{b['movers']}")
        lines.append("")
        lines.append("READING. Stating the base rate does raise raw accuracy, but it does so")
        lines.append("ONLY by collapsing the model onto the constant predictor. The base-rate")
        lines.append("arm's kappa against the measured dP-sign and its recall on the tasks")
        lines.append("that actually moved are the numbers that matter, and both are reported")
        lines.append("above. Accuracy that is achieved by reciting a prior the experimenter")
        lines.append("supplied is not evidence that dP is recoverable from the skill document.")
        agree_hb = sum(1 for t in h["tasks"]
                       if h["preds"][t].get("dominant_sip") == b["preds"][t].get("dominant_sip"))
        lines.append(f"\n  side note: the two arms still agree on dominant_sip "
                     f"{agree_hb}/{len(h['tasks'])} = {agree_hb/len(h['tasks']):.1%}, i.e. the")
        lines.append("  base-rate sentence moved the pass-rate head but barely moved the SIP head.")

    # ------------------------------------------------------------------ #
    # MOVEMENT DETECTION (direction-agnostic) + paired model-vs-model test
    # ------------------------------------------------------------------ #
    lines.append(f"\n{'='*78}\nMOVEMENT DETECTION: is 'this skill moved the pass rate at all'\n"
                 f"recoverable, even ignoring the direction?\n{'='*78}")
    lines.append("  A model that says 'moved' can be graded direction-agnostically. If its")
    lines.append("  'moved' calls land on genuinely-moved tasks more often than the corpus")
    lines.append("  prior (4/49 = 8.2%), it has SOME signal even when its signs are wrong.")
    lines.append(f"  {'model':32s} {'n_called_moved':>15s} {'of those, truly moved':>23s} "
                 f"{'precision':>10s} {'prior':>7s}")
    for m in ["claude-sonnet-4.5", "claude-sonnet-4.5-baserate", "gemini", "claude-opus-4.8"]:
        if m not in sup:
            continue
        r = sup[m]
        called = [t for t in r["tasks"]
                  if r["preds"][t].get("pass_rate_effect") in ("raise", "lower")]
        tp = sum(1 for t in called if truth[t]["dp_sign"] != 0)
        prior = r["movers"] / r["n"]
        prec = tp / len(called) if called else float("nan")
        lines.append(f"  {m:32s} {len(called):15d} {tp:23d} {prec:9.1%} {prior:6.1%}")
    lines.append("  Precision at or below the prior means the 'moved' calls carry no")
    lines.append("  information about which tasks moved -- the model is not merely")
    lines.append("  mis-signing a real detection, it is not detecting anything.")

    if "claude-sonnet-4.5" in sup and "gemini" in sup:
        s_, g_ = sup["claude-sonnet-4.5"], sup["gemini"]
        ts = sorted(set(s_["tasks"]) & set(g_["tasks"]))
        bb = sum(1 for t in ts
                 if (EFF2SIGN.get(s_["preds"][t].get("pass_rate_effect")) == truth[t]["dp_sign"])
                 and (EFF2SIGN.get(g_["preds"][t].get("pass_rate_effect")) != truth[t]["dp_sign"]))
        cc = sum(1 for t in ts
                 if (EFF2SIGN.get(s_["preds"][t].get("pass_rate_effect")) != truth[t]["dp_sign"])
                 and (EFF2SIGN.get(g_["preds"][t].get("pass_rate_effect")) == truth[t]["dp_sign"]))
        lines.append(f"\n  PAIRED test, Sonnet-4.5 vs gemini on dP-sign over the same {len(ts)} "
                     f"tasks:")
        lines.append(f"    Sonnet right / gemini wrong = {bb};  gemini right / Sonnet wrong = {cc}")
        lines.append(f"    exact McNemar p = {mcnemar_exact(bb, cc):.4g}")
        lines.append("    Both sit far below the 91.8% majority-class baseline, so any")
        lines.append("    Sonnet-vs-gemini difference is a difference between two failures.")

    # ------------------------------------------------------------------ #
    # CROSS-MODEL AGREEMENT
    # ------------------------------------------------------------------ #
    lines.append(f"\n{'='*78}\nCROSS-MODEL AGREEMENT: do the LLMs agree with EACH OTHER more\n"
                 f"than any of them agrees with CTA?\n{'='*78}")
    rows = []

    def sip_pairs(a_preds, b_preds, ts):
        return [(a_preds[t].get("dominant_sip"), b_preds[t].get("dominant_sip")) for t in ts]

    combos = [("claude-sonnet-4.5", "gemini"),
              ("claude-sonnet-4.5", "claude-opus-4.8"),
              ("gemini", "claude-opus-4.8"),
              ("claude-sonnet-4.5", "claude-sonnet-4.5-baserate")]
    for m1, m2 in combos:
        if m1 not in sup or m2 not in sup:
            continue
        ts = sorted(set(sup[m1]["tasks"]) & set(sup[m2]["tasks"]))
        pr = sip_pairs(sup[m1]["preds"], sup[m2]["preds"], ts)
        ag = sum(1 for a, b_ in pr if a == b_)
        k = cohen_kappa(pr, SIPS)
        pe = [(sup[m1]["preds"][t].get("pass_rate_effect"),
               sup[m2]["preds"][t].get("pass_rate_effect")) for t in ts]
        agd = sum(1 for a, b_ in pe if a == b_)
        rows.append((f"{m1} vs {m2}", len(ts), ag, ag / len(ts), k, agd, agd / len(ts)))

    # each model vs CTA on the SAME task sets, for a like-for-like contrast
    for m in ["claude-sonnet-4.5", "claude-sonnet-4.5-baserate", "gemini", "claude-opus-4.8"]:
        if m not in sup:
            continue
        ts = [t for t in sup[m]["tasks"]
              if truth[t]["total_sips"] > 0 and not truth[t]["is_tie"]]
        pr = [(truth[t]["dominant_sip"], sup[m]["preds"][t].get("dominant_sip")) for t in ts]
        ag = sum(1 for a, b_ in pr if a == b_)
        k = cohen_kappa(pr, SIPS)
        rows.append((f"{m} vs CTA", len(ts), ag, ag / len(ts), k, None, None))

    lines.append(f"  {'comparison':52s} {'n':>4s} {'SIP agree':>12s} {'kappa':>8s} {'dP agree':>12s}")
    for name, n, ag, agp, k, agd, agdp in rows:
        d = f"{agd}/{n} = {agdp:5.1%}" if agd is not None else "     (n/a)"
        lines.append(f"  {name:52s} {n:4d} {ag:3d}/{n} = {agp:5.1%} {k:+8.3f} {d:>12s}")

    lines.append("")
    lines.append("The comparison to make is the LLM-vs-LLM rows against the LLM-vs-CTA rows")
    lines.append("on comparable n. If the LLMs converge on each other while all of them")
    lines.append("diverge from CTA, the disagreement is not one model's idiosyncrasy: the")
    lines.append("document-only view is a stable but different signal from the trace-derived")
    lines.append("one. That is a claim about non-recoverability, NOT a claim that CTA is")
    lines.append("right -- LLM/CTA disagreement cannot adjudicate correctness in either")
    lines.append("direction. The human gold set is still required for that.")

    # 3-way per-task table on the 15 shared tasks
    shared3 = sorted(set(sup["claude-sonnet-4.5"]["tasks"])
                     & set(sup["gemini"]["tasks"])
                     & set(sup["claude-opus-4.8"]["tasks"])) if len(sup) >= 3 else []
    if shared3:
        lines.append(f"\n  per-task, the {len(shared3)} tasks all three models covered")
        lines.append(f"    {'task':34s} | {'CTA':>24s} | {'sonnet4.5':>24s} | "
                     f"{'gemini':>24s} | opus4.8")
        unan = 0
        for t in shared3:
            s = sup["claude-sonnet-4.5"]["preds"][t].get("dominant_sip")
            g = sup["gemini"]["preds"][t].get("dominant_sip")
            o = sup["claude-opus-4.8"]["preds"][t].get("dominant_sip")
            if s == g == o:
                unan += 1
            ct = truth[t]["dominant_sip_set"]
            lines.append(f"    {t:34s} | {str(ct[0] if ct else None):>24s} | {str(s):>24s} | "
                         f"{str(g):>24s} | {o}")
        lines.append(f"    all-three unanimous on {unan}/{len(shared3)} tasks; "
                     f"unanimous AND matching CTA on "
                     f"{sum(1 for t in shared3 if sup['claude-sonnet-4.5']['preds'][t].get('dominant_sip') == sup['gemini']['preds'][t].get('dominant_sip') == sup['claude-opus-4.8']['preds'][t].get('dominant_sip') == truth[t]['dominant_sip'])}")

    # ------------------------------------------------------------------ #
    # HEADLINE
    # ------------------------------------------------------------------ #
    lines.append(f"\n{'='*78}\nHEADLINE (rebuttal-ready, paper's own model)\n{'='*78}")
    s = sup.get("claude-sonnet-4.5")
    ss = out.get("claude-sonnet-4.5")
    if s and ss:
        lines.append(
            f"  dP-sign, n={s['n']}:  Sonnet-4.5 skill-doc-only {s['acc']}/{s['n']} = "
            f"{s['acc']/s['n']:.1%}   vs   always-predict-no-change "
            f"{s['maj']}/{s['n']} = {s['maj']/s['n']:.1%}  "
            f"(LLM is {s['maj']-s['acc']} tasks WORSE than trivial; kappa {s['kappa']:+.3f})")
        lines.append(
            f"  dominant SIP, n={ss['sip']['n']}:  Sonnet-4.5 {ss['sip']['llm']}/{ss['sip']['n']} = "
            f"{ss['sip']['llm']/ss['sip']['n']:.1%}   vs uniform 20.0%   vs prior-matched "
            f"{ss['sip']['prior_random']:.1%}   vs majority-class "
            f"{ss['sip']['majority']}/{ss['sip']['n']} = {ss['sip']['majority']/ss['sip']['n']:.1%};  "
            f"kappa {ss['sip']['kappa']:+.3f}")
        if b:
            lines.append(
                f"  base-rate arm, n={b['n']}: {b['acc']}/{b['n']} = {b['acc']/b['n']:.1%} "
                f"but {b['n_no_change']}/{b['n']} predictions are 'no_change' and it finds "
                f"{b['mover_hits']}/{b['movers']} movers (kappa {b['kappa']:+.3f}).")
    lines.append("\nCAVEATS TO KEEP IN THE REBUTTAL:")
    lines.append("  1. LOWER BOUND ONLY. No execution traces are shown to the model. The")
    lines.append("     reviewer asked for an LLM that READS BOTH TRACES; the raw .jsonl")
    lines.append("     traces do not exist in any accessible repo, so that experiment cannot")
    lines.append("     be run. This bounds document-only recoverability, nothing more.")
    lines.append("  2. The SIP half scores the LLM against CTA, not against humans, so it")
    lines.append("     cannot establish that CTA is correct -- only that its per-task output")
    lines.append("     is not reproducible from the skill document.")
    lines.append("  3. The dP-sign half is scored against MEASURED unit-test pass rates with")
    lines.append("     no CTA involvement. That is the clean, load-bearing number.")
    lines.append("  4. Part of the SIP gap is a CTA detector prior, not LLM error: CTA emits")
    lines.append("     procedural_scaffolding on only 11/522 fires because PS is suppressed")
    lines.append("     on unilateral_action divergences.")
    lines.append("  5. n is small (49 tasks, 1 instance/skill, r=1); CIs are wide. Model alias")
    lines.append("     is not the paper's pinned snapshot (see caveat at top).")

    txt = "\n".join(lines)
    (NEW / "scoring_report.txt").write_text(txt + "\n")

    # machine-readable
    tab = []
    for model, d, _ in ARMS:
        if model not in sup:
            continue
        for t in sup[model]["tasks"]:
            p = sup[model]["preds"][t]
            tab.append({
                "model": model, "task_id": t,
                "true_dp": truth[t]["pass_rate_delta"],
                "true_dp_sign": truth[t]["dp_sign"],
                "pred_effect": p.get("pass_rate_effect"),
                "pred_dp_sign": EFF2SIGN.get(p.get("pass_rate_effect")),
                "dp_correct": EFF2SIGN.get(p.get("pass_rate_effect")) == truth[t]["dp_sign"],
                "true_dominant_sip": truth[t]["dominant_sip"],
                "true_dominant_sip_set": truth[t]["dominant_sip_set"],
                "true_total_sips": truth[t]["total_sips"],
                "pred_dominant_sip": p.get("dominant_sip"),
                "sip_correct": (truth[t]["dominant_sip"] is not None
                                and truth[t]["dominant_sip"] == p.get("dominant_sip")),
                "pred_confidence": p.get("confidence"),
                "baseline_pass_rate": truth[t]["baseline_pass_rate"],
                "reasoning": p.get("reasoning"),
            })
    (NEW / "scoring_table.json").write_text(json.dumps(tab, indent=1))
    hdr = ["model", "task_id", "true_dp", "true_dp_sign", "pred_effect", "dp_correct",
           "true_dominant_sip", "pred_dominant_sip", "sip_correct", "pred_confidence",
           "true_total_sips", "baseline_pass_rate"]
    with open(NEW / "scoring_table.csv", "w") as f:
        f.write(",".join(hdr) + "\n")
        for r in tab:
            f.write(",".join(str(r[h]) for h in hdr) + "\n")

    summary = {m: {"dp": {k: v for k, v in sup[m].items()
                          if k not in ("preds", "tasks")},
                   "sip": out[m]["sip"] if m in out else None}
               for m in sup}
    (NEW / "summary_stats.json").write_text(json.dumps(summary, indent=1, default=str))
    print(txt)


if __name__ == "__main__":
    main()
